require:
  - rubocop-performance
  - rubocop-rails

AllCops:
  NewCops: enable
  TargetRubyVersion: 3.0.3

Style/Documentation:
  Enabled: false

Rails/FilePath:
  EnforcedStyle: arguments

I18n/RailsI18n:
  Enabled: true
I18n/GetText:
  Enabled: false